config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'
  resources :users, only: [:new, :create, :show] do
    resources :statistics
  end
  resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_LENGTH = (6..25)
  USERNAME_LENGTH = (5..15)

  validates_presence_of :username
  validates :username, length: USERNAME_LENGTH, uniqueness: true

  validates :password, length: PASSWORD_LENGTH, allow_nil: true

  has_many :monsters

  attr_reader :password

  def self.find_from_credentials(username, password)
    user = find_by(username: username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password_attempt)
    BCrypt::Password.new(password_digest).is_password?(password_attempt)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  private
  def sign_in(user)
    session[:session_token] = SecureRandom.urlsafe_base64
    user.update!(session_token: session[:session_token])
  end

  def sign_out
    return unless current_user
    current_user.update!(session_token: nil)
    session.delete(:session_token)
  end

  def current_user
    @current_user ||= find_current_user
  end

  def find_current_user
    session_token = session[:session_token]
    session_token && User.find_by(session_token: session_token)
  end

  def ensure_signed_in
    return if current_user
    # flash[:error] = 'Please sign in'
    redirect_to :root
  end

  def ensure_signed_out
    return unless current_user
    # flash[:error] = 'You are signed in'
    redirect_to user_path(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]
    user = User.find_from_credentials(username, password)
    if user
      sign_in(user)
      # flash[:notice] = "Welcome, #{username}"
      redirect_to user_statistics_path(user)
    else
      flash[:error] = "User does not exist"
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    # flash[:notice] = 'Signed out'
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end #END OF CLASS

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  before_action :ensure_signed_in
  before_action :load_statistics, only: [:index, :show, :edit, :update, :destroy, :new]

  def new
    @statistic = Statistic.new
    @user = current_user
  end

  def index
    @statistic = Statistic.where(user_id: params[:user_id])
  end

  def create
    @statistic = Statistic.new(create_params)
    @statistic.user = current_user

    if @statistic.save
      flash[:notice] = 'Stats recorded!'
      redirect_to user_statistics_path
    else
      flash[:error] = @statistic.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @statistic.update(update_params)
      flash[:notice] = 'Statistic updated!'
      redirect_to satistics_path(@statistic)
    else
      flash[:error] = @statistic.errors.full_messages.join(', ')
      render :edit
    end
  end


  def show
    @statistic = Statistic.find_by(id: params[:id])
  end

  def destroy
    @statistic.destroy!

    flash[:notice] = "#{@statistic.name} deleted!"
    redirect_to user_path
  end

  private

  def create_params
    params.require(:statistic).permit(:sleep, :happiness, :energy, :stress, :optimism, :wins, :losses)
  end

  def update_params
    params.require(:user_id).permit(:wins)
  end

  def load_statistics
    @statistic = Statistic.find_by(user_id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show] #:index
  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      sign_in(@user)
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  # def index
  #   @users = User.all  DO WE WANT EVERYONE MOOD TO BE PUBLIC??
  # end

  def show
    @user = User.find(params[:id])
  end

  private

  def create_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= button_to 'Log out', session_path, method: :delete %>
    <% end %>

    <% if flash[:notice].present? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:error].present? %>
      <div class="errors">
        <b>Errors:</b>
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/statistics/edit.html.erb
<h2>Update Disposition</h2>

<%= form_for [@user, @statistic] do |form| %>

  <%= label_tag :sleep %>

  <b><%= @monster.name %></b>
  <br>
  <%= label_tag :happiness %>
  <br>
  <%= form.text_area :wins, placeholder: 'Wins' %>
  <%= form.text_area :wins, placeholder: 'Losses' %>


  <br>
  <%= submit_tag 'Submit' %>
<% end %>

app/views/statistics/index.html.erb
<h2>Index Page</h2>

<div class="index-button"><%= link_to "create new disposition", new_user_statistic_path %></div>

  <% @statistic.each do |item| %>
    <div class="indexes">
      <div class="index-preview">
        <p> Disposition <%= item[:id] %> </p>
        <p> <%= item[:created_at] %> </p>
      </div>

      <div class="index-button"><%= link_to "view", user_statistic_path(item[:user_id],item[:id]) %></div>

    </div>
  <% end %>

app/views/statistics/new.html.erb
<button><%= link_to "Back", user_statistics_path(current_user) %></button>

<h2>New disposition page</h2>

<%= form_for [@user, @statistic] do |form| %>
  <div>Sleep: <br><%= form.number_field(:sleep, in: 0..24.0, step: 1, placeholder:0) %></div>
  <div>Happiness: <br><%= form.number_field(:happiness, in: 0..10.0, step: 1, placeholder:0) %></div>
  <div>Energy: <br><%= form.number_field(:energy, in: 0..10.0, step: 1, placeholder:0) %></div>
  <div>Stress: <br><%= form.number_field(:stress, in: 0..10.0, step: 1, placeholder:0) %></div>
  <div>Optimism:<br> <%= form.number_field(:optimism, in: 0..10.0, step: 1, placeholder:0) %></div>
  <br>
  <%= form.text_area :wins, placeholder: 'Wins' %>
  <%= form.text_area :losses, placeholder: 'Losses' %>

  <br>
  <%= submit_tag 'Submit' %>
<% end %>

app/views/statistics/show.html.erb
<h1> Disposition: <%= @statistic.id %> </h1>
  <h2><%= @statistic.created_at %></h2>
  <p> Sleep: <%= @statistic.sleep %> </p>
  <p> Happiness: <%= @statistic.happiness %> </p>
  <p> Energy: <%= @statistic.energy %> </p>
  <p> Stress: <%= @statistic.stress %> </p>
  <p> Optimism: <%= @statistic.optimism %> </p>
  <p> Wins: <%= @statistic.wins %> </p>
  <p> Losses: <%= @statistic.losses %> </p>

  <div class="index-button"><%= link_to "Update", edit_user_statistic_path(@statistic.id) %></div>

app/views/users/index.html.erb
<h3>Profile</h3>


  <% @users.each do |user| %>
    <h3 class="soft-heading">user.username</h3>
    <p class="link"><%= link_to user.username, user_path(user) %></p>
  <% end %>

app/views/users/new.html.erb
<h2>Register</h2>

<%= form_for @user do |form| %>
<%= form.text_field :username,
        placeholder: "Username",
        required: true,
        minlength: User::USERNAME_LENGTH.begin,
        maxlength: User::USERNAME_LENGTH.end
  %>

<%= form.password_field :password,
        placeholder: "Password",
        required: true,
        minlength: User::PASSWORD_LENGTH.begin,
        maxlength: User::PASSWORD_LENGTH.end
  %>
<%= submit_tag 'Submit' %>
<% end %>
<%= link_to 'Login', new_session_path %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s Mood</h1>